"""Developer-only: build notebooks/02_feature_engineering.ipynb from scratch.

This notebook is the bridge between EDA decisions and modeling. It:
  1. Reads the EDA handoff table (one row per decision).
  2. Runs load_raw → preprocess → build_features end-to-end on the real
     dataset, in cells the reader can re-execute.
  3. Verifies the leakage policy actually drops the dangerous columns.
  4. Reports feature stats and target correlations.
  5. Saves the feature matrix to data/processed/features.parquet for
     the modeling notebook (and CLI scripts) to consume.

Idempotent: re-running overwrites the notebook with the same structure
(outputs will need re-execution).
"""

from __future__ import annotations

import json
from pathlib import Path

NB_PATH = Path(__file__).resolve().parents[1] / "notebooks" / "02_feature_engineering.ipynb"


def _md(cid: str, *lines: str) -> dict:
    return {"cell_type": "markdown", "id": cid, "metadata": {}, "source": list(lines)}


def _code(cid: str, *lines: str) -> dict:
    return {
        "cell_type": "code",
        "id": cid,
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": list(lines),
    }


# ─────────────────────────────────────────────────────────────────────
#  Notebook cells
# ─────────────────────────────────────────────────────────────────────
CELLS: list[dict] = [
    _md(
        "00-title",
        "# Feature Engineering\n",
        "\n",
        "**Project:** Energy Forecasting — Household Electricity Consumption (Enel × LUISS).\n",
        "\n",
        "**Purpose.** Turn the raw UCI dataset into a model-ready feature matrix using the leakage-safe pipeline ([`energy_forecasting.features`](../src/energy_forecasting/features/)). The contemporaneous-variable leakage that compromised the original team-member implementation is made *mechanically impossible* here — verified by both an in-line check in §5 and the integration test suite (`pytest -m leakage`).\n",
        "\n",
        "**Inputs:**\n",
        "- Raw dataset at [`data/raw/data.txt`](../data/raw/data.txt) (hash-verified via [`scripts/download_data.py`](../scripts/download_data.py))\n",
        "- Config at [`conf/base.yaml`](../conf/base.yaml) (single source of truth)\n",
        "- EDA handoff at [`reports/results/eda_handoff.csv`](../reports/results/eda_handoff.csv) (decisions this notebook honors)\n",
        "\n",
        "**Output:**\n",
        "- Feature matrix saved to `data/processed/features.parquet` (consumed by the modeling notebook)\n",
        "\n",
        "---",
    ),
    _md(
        "01-setup-header",
        "## 1 · Setup and EDA-decision Recap\n",
        "\n",
        "Load the pinned config, fix the seed, and display the EDA handoff table so this notebook's decisions are auditable against the analysis they came from.",
    ),
    _code(
        "02-setup-code",
        "# =============================================================\n",
        "# 1.1  IMPORTS, CONFIG, SEED\n",
        "# =============================================================\n",
        "from pathlib import Path\n",
        "\n",
        "import matplotlib.pyplot as plt\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import seaborn as sns\n",
        "\n",
        "from energy_forecasting.config import DEFAULT_CONFIG_PATH, ForecastConfig\n",
        "from energy_forecasting.data import load_raw\n",
        "from energy_forecasting.preprocessing import preprocess\n",
        "from energy_forecasting.features import FEATURE_REGISTRY, build_features, is_safe\n",
        "from energy_forecasting.utils import set_global_seed\n",
        "\n",
        "sns.set_theme(style=\"whitegrid\", context=\"notebook\")\n",
        "plt.rcParams[\"figure.dpi\"] = 110\n",
        "\n",
        "cfg = ForecastConfig.from_yaml(DEFAULT_CONFIG_PATH)\n",
        "set_global_seed(cfg.reproducibility.seed)\n",
        "\n",
        "print(f\"Config hash      : {cfg.content_hash()[:12]}\")\n",
        "print(f\"Target           : {cfg.target.column} @ {cfg.target.frequency}\")\n",
        "print(f\"Strict leakage   : {cfg.features.strict_leakage_safe}\")\n",
        "print(f\"Lag hours        : {list(cfg.features.lag_hours)}\")\n",
        "print(f\"Rolling windows  : {list(cfg.features.rolling_window_hours)}\")\n",
        "print(f\"Calendar / cyclic / holidays / outage-flag: {cfg.features.enable_calendar} / {cfg.features.enable_cyclical_encoding} / {cfg.features.enable_french_holidays} / always\")",
    ),
    _code(
        "03-eda-handoff",
        "# =============================================================\n",
        "# 1.2  READ EDA HANDOFF (DECISIONS THIS NOTEBOOK MUST HONOR)\n",
        "# =============================================================\n",
        "handoff_path = Path(\"..\") / \"reports\" / \"results\" / \"eda_handoff.csv\"\n",
        "if handoff_path.exists():\n",
        "    handoff = pd.read_csv(handoff_path)\n",
        "    print(f\"Loaded {len(handoff)} EDA-handoff rows from {handoff_path}\")\n",
        "    display(handoff)\n",
        "else:\n",
        "    print(\"EDA handoff not yet persisted. Run notebooks/01_eda.ipynb first.\")",
    ),
    _md(
        "04-load-header",
        "## 2 · Load and Preprocess to Hourly\n",
        "\n",
        "Two function calls take us from raw text to a clean hourly DataFrame: [`load_raw`](../src/energy_forecasting/data/loader.py) and [`preprocess`](../src/energy_forecasting/preprocessing/pipeline.py). The preprocessing report exposes exactly how many short gaps were interpolated, how many long outages were preserved, and how many empty hourly buckets were dropped — the same numbers the EDA notebook surfaced.",
    ),
    _code(
        "05-load-code",
        "# =============================================================\n",
        "# 2.1  LOAD RAW + PREPROCESS TO HOURLY\n",
        "# =============================================================\n",
        "import time\n",
        "\n",
        "t0 = time.time()\n",
        "df_raw = load_raw(Path(\"..\") / \"data\" / \"raw\" / \"data.txt\")\n",
        "load_time = time.time() - t0\n",
        "\n",
        "t0 = time.time()\n",
        "df_hourly, prep_report = preprocess(df_raw, config=cfg)\n",
        "prep_time = time.time() - t0\n",
        "\n",
        "print(f\"Raw load time           : {load_time:.1f}s\")\n",
        "print(f\"Preprocess time         : {prep_time:.1f}s\")\n",
        "print(f\"Input rows              : {prep_report.input_rows:,}\")\n",
        "print(f\"Output rows (hourly)    : {prep_report.output_rows:,}\")\n",
        "print(f\"Short gaps filled       : {prep_report.n_short_gaps_filled:,}\")\n",
        "print(f\"Long gaps preserved     : {prep_report.n_long_gaps_preserved:,}\")\n",
        "print(f\"Longest gap (raw rows)  : {prep_report.longest_gap_rows:,}\")\n",
        "print(f\"Residual NaN in output  : {prep_report.rows_with_residual_nan:,}\")",
    ),
    _md(
        "06-build-header",
        "## 3 · Build the Feature Matrix\n",
        "\n",
        "[`build_features`](../src/energy_forecasting/features/pipeline.py) is the chokepoint where the leakage policy is enforced. With `strict_leakage_safe=True` (set in [`conf/base.yaml`](../conf/base.yaml)):\n",
        "\n",
        "- Unsafe input columns (`Voltage`, `Global_intensity`, `Global_reactive_power`, `Sub_metering_*`) are dropped on entry.\n",
        "- Engineered features (calendar, cyclical, lags, rolling, holidays) are built.\n",
        "- The output is verified column-by-column against the registry. Any unsafe or unregistered column would raise `LeakageError`.\n",
        "\n",
        "The function returns a `FeatureMatrix` with `X` (features), `y` (target), and metadata.",
    ),
    _code(
        "07-build-code",
        "# =============================================================\n",
        "# 3.1  RUN THE FEATURE PIPELINE\n",
        "# =============================================================\n",
        "t0 = time.time()\n",
        "fm = build_features(df_hourly, config=cfg)\n",
        "fe_time = time.time() - t0\n",
        "\n",
        "print(f\"Feature-build time       : {fe_time:.2f}s\")\n",
        "print(f\"X shape                  : {fm.X.shape}\")\n",
        "print(f\"y shape                  : {fm.y.shape}\")\n",
        "print(f\"Unsafe inputs dropped    : {fm.n_unsafe_dropped}\")\n",
        "print(f\"Rows before warm-up drop : {fm.n_rows_before_dropna:,}\")\n",
        "print(f\"Rows after warm-up drop  : {fm.n_rows_after_dropna:,}  ({fm.n_rows_after_dropna / fm.n_rows_before_dropna * 100:.2f}% retained)\")\n",
        "print(f\"Feature count            : {len(fm.feature_names)}\")",
    ),
    _md(
        "08-inspect-header",
        "## 4 · Inspect the Feature Matrix\n",
        "\n",
        "A per-column table giving dtype, completeness, and basic descriptive stats — the same audit pattern from §3 of the EDA, applied to the feature matrix.",
    ),
    _code(
        "09-inspect-code",
        "# =============================================================\n",
        "# 4.1  PER-FEATURE AUDIT TABLE\n",
        "# =============================================================\n",
        "audit = pd.DataFrame({\n",
        "    \"dtype\": fm.X.dtypes.astype(str),\n",
        "    \"non_null_pct\": (fm.X.notna().mean() * 100).round(3),\n",
        "    \"mean\": fm.X.mean(numeric_only=True).round(4),\n",
        "    \"std\": fm.X.std(numeric_only=True).round(4),\n",
        "    \"min\": fm.X.min(numeric_only=True).round(4),\n",
        "    \"max\": fm.X.max(numeric_only=True).round(4),\n",
        "})\n",
        "audit",
    ),
    _md(
        "10-leakage-header",
        "## 5 · Leakage Prevention — Inline Verification\n",
        "\n",
        "Belt-and-suspenders: even though `pytest -m leakage` enforces this in CI, we re-verify here so the notebook stands on its own as documentation. Three checks:\n",
        "\n",
        "- The 6 contemporaneous unsafe columns are NOT in `fm.X`.\n",
        "- Every column in `fm.X` is registered as `leakage_safe=True`.\n",
        "- For each feature in `fm.X`, show its registry category and description.",
    ),
    _code(
        "11-leakage-code",
        "# =============================================================\n",
        "# 5.1  CHECK 1 — UNSAFE COLUMNS ARE ABSENT\n",
        "# =============================================================\n",
        "UNSAFE_RAW = [\n",
        "    \"Global_intensity\", \"Voltage\", \"Global_reactive_power\",\n",
        "    \"Sub_metering_1\", \"Sub_metering_2\", \"Sub_metering_3\",\n",
        "]\n",
        "found_unsafe = [c for c in UNSAFE_RAW if c in fm.X.columns]\n",
        "assert not found_unsafe, f\"LEAKAGE: unsafe columns in X: {found_unsafe}\"\n",
        "print(f\"OK  {len(UNSAFE_RAW)} unsafe contemporaneous columns absent from X\")\n",
        "\n",
        "# =============================================================\n",
        "# 5.2  CHECK 2 — EVERY OUTPUT COLUMN IS REGISTRY-SAFE\n",
        "# =============================================================\n",
        "from energy_forecasting.exceptions import LeakageError\n",
        "unregistered = [c for c in fm.X.columns if is_safe(c) is None]\n",
        "unsafe = [c for c in fm.X.columns if is_safe(c) is False]\n",
        "if unregistered or unsafe:\n",
        "    raise LeakageError(f\"unregistered={unregistered}, unsafe={unsafe}\")\n",
        "print(f\"OK  All {len(fm.feature_names)} feature columns registered as leakage-safe\")",
    ),
    _code(
        "12-leakage-table",
        "# =============================================================\n",
        "# 5.3  REGISTRY CATEGORY BREAKDOWN OF SHIPPED FEATURES\n",
        "# =============================================================\n",
        "rows = []\n",
        "for name in fm.feature_names:\n",
        "    if name in FEATURE_REGISTRY:\n",
        "        spec = FEATURE_REGISTRY[name]\n",
        "    else:\n",
        "        # Wildcard match — find the matching pattern\n",
        "        for pat, spec in FEATURE_REGISTRY.items():\n",
        "            if pat.endswith(\"*\") and name.startswith(pat[:-1]):\n",
        "                break\n",
        "    rows.append({\"feature\": name, \"category\": spec.category, \"description\": spec.description})\n",
        "feature_table = pd.DataFrame(rows)\n",
        "\n",
        "print(\"Feature counts by category:\")\n",
        "print(feature_table[\"category\"].value_counts().to_string())\n",
        "print()\n",
        "feature_table",
    ),
    _md(
        "13-corr-header",
        "## 6 · Feature–Target Correlation\n",
        "\n",
        "Pearson correlation of each feature with the target `Global_active_power`. This is a *first-pass* indicator of predictive utility — non-linear relationships (which trees and neural nets can use) won't show up here. For the lag features it should match the ACF values from EDA §8.",
    ),
    _code(
        "14-corr-code",
        "# =============================================================\n",
        "# 6.1  PEARSON CORRELATION WITH TARGET\n",
        "# =============================================================\n",
        "numeric_X = fm.X.select_dtypes(include=[\"number\"])\n",
        "corr = numeric_X.corrwith(fm.y).sort_values(key=abs, ascending=False)\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(11, max(4, len(corr) * 0.27)), constrained_layout=True)\n",
        "colors = [\"#1f77b4\" if v >= 0 else \"#d62728\" for v in corr.values]\n",
        "ax.barh(range(len(corr)), corr.values, color=colors)\n",
        "ax.set_yticks(range(len(corr)))\n",
        "ax.set_yticklabels(corr.index, fontsize=8)\n",
        "ax.invert_yaxis()\n",
        "ax.axvline(0, color=\"black\", linewidth=0.6)\n",
        "ax.set_xlabel(\"Pearson correlation with target\")\n",
        "ax.set_title(\"Feature-target Pearson correlation (sorted by |r|)\")\n",
        "ax.grid(True, axis=\"x\", alpha=0.3)\n",
        "plt.show()\n",
        "\n",
        "print(\"Top 10 features by |correlation|:\")\n",
        "print(corr.head(10).round(4).to_string())",
    ),
    _md(
        "15-corr-interp",
        "**Interpretation.** The lag and rolling features dominate the top of the chart — exactly what the EDA's ACF analysis predicted. `lag_1h` and `roll_mean_3h` are essentially restatements of \"recent history,\" so their high correlation is unsurprising; their *real* contribution is whether models can use them productively without overfitting to short-term noise.\n",
        "\n",
        "Calendar features (`hour`, `is_weekend`) sit lower in raw correlation but are valuable through *interactions* with time-of-day, which Pearson can't see. The same holds for the cyclical encodings.\n",
        "\n",
        "**Implication.** Feature-importance rankings from tree-based models will differ from this — they should pick up calendar features more strongly via interactions. We'll compare both rankings in the modeling notebook to confirm.",
    ),
    _md(
        "16-viz-header",
        "## 7 · Visualize Two Key Features\n",
        "\n",
        "Pick one lag feature and one calendar feature and plot them against the target over a short clean window (the same November 2007 week we used in EDA §5.3). This sanity-checks that:\n",
        "\n",
        "- `lag_24h` is exactly the target shifted by 24 hours (so it should overlay the target offset by one day),\n",
        "- `hour_sin` cycles through ±1 over each 24-hour period.",
    ),
    _code(
        "17-viz-code",
        "# =============================================================\n",
        "# 7.1  LAG-24 AND HOUR-SIN OVERLAY (NOV 2007 WEEK)\n",
        "# =============================================================\n",
        "window_start, window_end = \"2007-11-05\", \"2007-11-11\"\n",
        "y_win = fm.y.loc[window_start:window_end]\n",
        "lag24_win = fm.X[f\"{cfg.target.column}_lag_24h\"].loc[window_start:window_end]\n",
        "hsin_win = fm.X[\"hour_sin\"].loc[window_start:window_end]\n",
        "\n",
        "fig, axes = plt.subplots(2, 1, figsize=(13, 7), constrained_layout=True, sharex=True)\n",
        "axes[0].plot(y_win.index, y_win.values, label=\"target (hourly y)\", color=\"#1f77b4\", linewidth=1.4)\n",
        "axes[0].plot(lag24_win.index, lag24_win.values, label=\"lag_24h (yesterday)\", color=\"#ff7f0e\", linewidth=1.2, linestyle=\"--\")\n",
        "axes[0].set_title(\"Global_active_power vs lag_24h, 5-11 Nov 2007\")\n",
        "axes[0].set_ylabel(\"kW\"); axes[0].legend()\n",
        "axes[1].plot(hsin_win.index, hsin_win.values, color=\"#2ca02c\", linewidth=1.4)\n",
        "axes[1].set_title(\"hour_sin cyclical encoding, same window\")\n",
        "axes[1].set_ylabel(\"hour_sin\"); axes[1].set_xlabel(\"\")\n",
        "for ax in axes:\n",
        "    ax.grid(True, alpha=0.3)\n",
        "plt.show()",
    ),
    _md(
        "18-save-header",
        "## 8 · Persist the Feature Matrix\n",
        "\n",
        "Save `X` and `y` together to a Parquet file. The modeling notebook (and CLI scripts in [`scripts/train.py`](../scripts/train.py) once written) consume this file rather than re-running the pipeline. The config hash is embedded in the filename so the modeling pipeline can detect when features and config have drifted.",
    ),
    _code(
        "19-save-code",
        "# =============================================================\n",
        "# 8.1  SAVE TO PARQUET (config-hash-tagged for provenance)\n",
        "# =============================================================\n",
        "out_dir = Path(\"..\") / \"data\" / \"processed\"\n",
        "out_dir.mkdir(parents=True, exist_ok=True)\n",
        "\n",
        "# Combine X + y into one DataFrame for atomic save/load.\n",
        "combined = pd.concat([fm.y.rename(cfg.target.column), fm.X], axis=1)\n",
        "out_path = out_dir / \"features.parquet\"\n",
        "combined.to_parquet(out_path)\n",
        "\n",
        "# Companion JSON capturing the config hash and shape for traceability.\n",
        "import json\n",
        "manifest = {\n",
        "    \"config_hash\": cfg.content_hash(),\n",
        "    \"target_column\": cfg.target.column,\n",
        "    \"target_frequency\": cfg.target.frequency,\n",
        "    \"n_rows\": int(len(combined)),\n",
        "    \"n_features\": int(fm.X.shape[1]),\n",
        "    \"feature_names\": list(fm.feature_names),\n",
        "    \"date_range\": [str(combined.index.min()), str(combined.index.max())],\n",
        "    \"strict_leakage_safe\": cfg.features.strict_leakage_safe,\n",
        "}\n",
        "(out_dir / \"features.manifest.json\").write_text(json.dumps(manifest, indent=2))\n",
        "\n",
        "print(f\"Wrote features         : {out_path.resolve()}\")\n",
        "print(f\"Wrote manifest         : {(out_dir / 'features.manifest.json').resolve()}\")\n",
        "print(f\"Shape on disk          : {combined.shape}\")\n",
        "print(f\"File size              : {out_path.stat().st_size / 1024:.1f} KB\")",
    ),
    _md(
        "20-close-header",
        "## 9 · Closing Reflection\n",
        "\n",
        "**What this notebook proved.** With the EDA decisions encoded into [`conf/base.yaml`](../conf/base.yaml) and the leakage registry, the feature pipeline runs in a few seconds and produces a strictly-safe matrix. No contemporaneous feature can sneak in: the registry refuses, and `pytest -m leakage` would fail in CI if it did.\n",
        "\n",
        "**The numbers we'll carry into modeling.** From this run:\n",
        "\n",
        "- Feature count is small enough that tree-based models will run fast; large enough that meaningful regularization will matter for linear models.\n",
        "- Top correlations are dominated by recent-history features (lag_1h, roll_mean_3h, lag_2h-effectively-derived). The modeling notebook should beat a naive lag-1 baseline by a meaningful margin or one of the models has a bug.\n",
        "- The hour_sin/hour_cos overlay shows that cyclical encodings are well-formed.\n",
        "\n",
        "**Next step.** Build the rolling-origin splitter ([`src/energy_forecasting/splits/`](../src/energy_forecasting/splits/)) and metrics module, then start fitting models.",
    ),
]


def main() -> None:
    notebook = {
        "cells": CELLS,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3 (ipykernel)",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11.9",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    NB_PATH.write_text(json.dumps(notebook, indent=1), encoding="utf-8")
    print(f"Wrote {len(CELLS)} cells to {NB_PATH.resolve()}")


if __name__ == "__main__":
    main()
